### ISSUE TITLE
Can't upload Files to google drive .

### ISSUE THREAD

**Issue by scorppio** [biplobsd/Google-Colab-CloudTorrent#1]
I can 't upload files to google Drive . Even though I click on open Example and install what was there after that I restart . Still I can't upload files to my google drive . 
The Error was still like this . 
`ImportError                               Traceback (most recent call last)

<ipython-input-2-d226d4ea7d8d> in <module>()
     47 
     48 
---> 49 from rlab_utils import (
     50     displayOutput,
     51     checkAvailable,

ImportError: cannot import name 'PATH_RClone_Log'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.`

**Comment by biplobsd** [comment]
Update your script. fixed !
