### ISSUE TITLE
关于下载器容量恢复问题

### ISSUE THREAD

**Issue by xiaobei0606** [biplobsd/Google-Colab-CloudTorrent#13]
biplobsd  你好  感谢你为我们提供这样一个福利 之后还更新了   提供了下载的路径  很方便 我有个问题   那个下载器 的容量    我下载完东西之后   不是自动转移到谷歌云盘内了吗   那个下载器的容量为什么不能恢复到74g 呢 ？   如果不恢复的话  每次用完就得恢复出厂设置  这样不方便  希望biplobsd 大神  可以看一下    可否更新呢  谢谢   
![QQ截图20200311203927](https://user-images.githubusercontent.com/61942124/76418174-1f282880-63d9-11ea-9747-7141503e7683.png)

**Comment by biplobsd** [comment]
I'm just Google Translated you problem text.
If i correct, you just want to say main download path set to gdrive path. It is posiable to change simple-torrent configs file.

Open simple-torrent cell in code view and goto line 106 .
![image](https://user-images.githubusercontent.com/43641536/76423224-a45b0f80-63d0-11ea-9c03-96a55b207fef.png)
Change the line accounding to your want.

Now save Notebook to your gdrive. 
![image](https://user-images.githubusercontent.com/43641536/76423647-51358c80-63d1-11ea-96d3-86952d67fd94.png)

Everytime open your changed notebook from gdrive notebook.
It is save your time.

**Comment by tofuliang** [comment]
What he means that when a download mission is completed and moved to google drive,files in "downloads/" was not deleted and it take space of the 74GB.
And could this script removes thoese files automatically?

**Comment by biplobsd** [comment]
File was moved to you gdrive but gdrive upload cache not deleted auto. That's why this is taking space.
I recommend to using rclone. Rclone will delete cache file when file transmision done.
