### ISSUE TITLE
How to convert a file to rar format ?

### ISSUE THREAD

**Issue by innowebka** [biplobsd/Google-Colab-CloudTorrent#14]
**help me !**

**Comment by innowebka** [comment]
and how to add mounted drive file to PATH_TO_FILE ?

**Comment by biplobsd** [comment]
> and how to add mounted drive file to PATH_TO_FILE ?
![image](https://user-images.githubusercontent.com/43641536/79124202-a47a7080-7dbd-11ea-8a0e-052b19402a51.png)


Mega currently not working well. Don't use this. Use other one

**Comment by innowebka** [comment]
found the solution wroking well.
the input username need to change manually in code to email

**Comment by innowebka** [comment]
**step1: Converted file to Zip (screenshot 1)** 

![Screenshot](https://user-images.githubusercontent.com/57298213/79771653-b70c2100-834c-11ea-8b95-7c487f61d977.png)

**step2: Extrected the zip (screenshot 2)**
![Screenshot](https://user-images.githubusercontent.com/57298213/79771850-00f50700-834d-11ea-9647-0ebf07bcfd01.png)

for testing i named the zip file as MINI

**when i convert to zip and extrect the zip file, i need file with path like below screnshot ? so how to do it ?**
![Screenshot2](https://user-images.githubusercontent.com/57298213/79772722-0acb3a00-834e-11ea-9575-5f19f504522d.png)

**mounted the grive and when  i try to it convert it converts the whole gdrive so i need help!!**

**i just wanna make a zip file like zipfilename/file not like zipFileName/content/grive/file**

**Comment by biplobsd** [comment]
4344f4a72afdcc10375f68771ba0444a82367696 is that you want ?
