### ISSUE TITLE
How can we add other cloud-torrent alternatives in it?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [biplobsd/Google-Colab-CloudTorrent#2]
Can you tell how to add
https://github.com/ParveenBhadooOfficial/Bhadoo-Cloud
or
https://github.com/boypt/simple-torrent

**Comment by biplobsd** [comment]
I replaced Cloud Torrent by Simple torrent. Now you can using  simple torrent on my colab script!

**Comment by ParveenBhadooOfficial** [comment]
HURRAAAAAAAHHHHHHH
