### ISSUE TITLE
Feature Request - convert mkv to mp4

### ISSUE THREAD

**Issue by innowebka** [biplobsd/Google-Colab-CloudTorrent#22]
**Please Add a feature to convert .mkv file to .mp4 file**

**Comment by innowebka** [comment]
Tried this https://pypi.org/project/PythonVideoConverter/ **python converter**
**pip install PythonVideoConverter**
but it converts the files too slow.

**Comment by innowebka** [comment]
so add a feature that converts videos to quick

**Comment by biplobsd** [comment]
☹️

**Comment by kaizoku75** [comment]
nice idea softsub to hard sub
